// src/client/src/pages/Login.jsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useDispatch } from 'react-redux';
import ValidationError from '../features/ValidationError';
import { loginUser } from '../app/actions/account/loginUser';

function Login() {
  const [errors, setErrors] = useState([]);
  const navigate = useNavigate();
  const dispatch = useDispatch();
  let formData = {
    email: '',
    password: '',
  };
  const handleChange = e => {
    formData = {
      ...formData,
      [e.target.name]: e.target.value.trim(),
    };
  };

  const handleSubmit = event => {
    event.preventDefault();
    setErrors([]);
    const validationErrors = ValidationError.Validate(formData);
    if (validationErrors.length) {
      setErrors(validationErrors);
      return;
    }
    dispatch(loginUser(formData));
    return navigate('/recipes');
  };
  const failedValidationStyles = {
    'outline': '1px solid red',
  };


  return (
    <div className='container'>
      <form action='#' className='login' onSubmit={handleSubmit}>
        <h3 className='login__heading'>Login</h3>
        <div >
          <label htmlFor='name' className='login__label'>Email</label><br />
          <input
            type='text'
            name='email'
            id='name'
            className='login__input'
            placeholder='example@email.com'
            required
            onChange={handleChange}
            style={errors.some(error => error.type === 'email') ? failedValidationStyles : {}}
          />
          {errors.some(error => error.type === 'email') ? <p style={{ 'color': 'red' }}>Invalid email</p> : <></>}
        </div>
        <div>
          <label htmlFor='pass' className='login__label'>Password</label><br />
          <input
            type='password'
            name='password'
            id='pass'
            className='login__input'
            required
            onChange={handleChange}
            style={errors.some(error => error.type === 'password') ? failedValidationStyles : {}}
          />
          {errors.some(error => error.type === 'password') ? <p style={{ 'color': 'red' }}>Invalid password</p> : <></>}
        </div>
        <Link to='/register' className='login__register'
        >Don`t have an account?</Link>
        <button type='submit' className='login__submit'>Login</button>
      </form>
    </div>);
}

export default Login;

// src/client/src/views/Login.vue
<template>
  <div class="container">
    <form action="#" class="login">
      <h3 class="login__heading">Login</h3>
      <div>
        <label for="name" class="login__label">Email</label><br />
        <input
          type="text"
          name=""
          id="name"
          class="login__input"
          placeholder="example@email.com"
          required
        />
      </div>
      <div>
        <label for="pass" class="login__label">Password</label><br />
        <input type="text" name="" id="pass" class="login__input" required />
      </div>
      <a href="#" class="login__register">Don`t have an account?</a>
      <button type="submit" class="login__submit">Login</button>
    </form>
  </div>
</template>

<script>
export default {
  name: 'Login',
};
</script>

<style scoped></style>
