// src/client/src/components/Banner.jsx
import React from 'react';
import { Link } from 'react-router-dom';

function Banner() {
  return (
    <main className='container'>
      <div className='banner'>
        <h3>Cyberchef - light and easy to use cooking ideas app</h3>
        <p>Start now</p>
        <div className='banner__buttons'>
          <Link to='/login' className='banner__href'>Login</Link>
          <Link to='/register' className='banner__href'>Register
          </Link>
        </div>
      </div>
    </main>
  );
}

export default Banner;

// src/client/src/components/Banner.vue
<template>
  <main class="container">
    <div class="banner">
      <h3>Cyberchef - light and easy to use cooking ideas app</h3>
      <p>Start now</p>
      <div class="banner__buttons">
        <router-link to="/login" class="banner__href">Login</router-link>
        <router-link to="/register" class="banner__href">Register</router-link>
      </div>
    </div>
  </main>
</template>

<script>
export default {
  name: 'Banner',
};
</script>

<style scoped></style>
