// src/client/src/components/Footer.jsx
import React from 'react';

const Footer = () => (
  <footer className="footer">
    <div className="footer__container">
      <div className="footer__left">
        <p className="footer__desc">
          Copyright ©Readme Experts 2023 All rights reserved
        </p>
      </div>
      <div className="footer__right">
        <a
          href="https://github.com/readme-experts/cyberchef"
          className="footer__link"
        >Github</a
        >
      </div>
    </div>
  </footer>
);

export default Footer;

// src/client/src/components/Footer.vue
<template>
  <footer class="footer">
    <div class="footer__container">
      <div class="footer__left">
        <p class="footer__desc">
          Copyright ©Readme Experts 2021 All rights reserved
        </p>
      </div>
      <div class="footer__right">
        <a
          href="https://github.com/readme-experts/cyberchef"
          class="footer__link"
          >Github</a
        >
      </div>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'Footer',
};
</script>

<style scoped></style>
