// src/client/src/components/Recipe.jsx
import React from 'react';
import PropTypes from 'prop-types';
import { Link } from 'react-router-dom';

Recipe.propTypes = {
  recipe: PropTypes.shape({
    id: PropTypes.number,
    name: PropTypes.string,
    image_link: PropTypes.string,
    products: PropTypes.string,
  }),
  clickHandler: PropTypes.func,
};

function Recipe({ recipe, clickHandler }) {
  return (
    <div className='content__recipes'>
      <div className='content__recipe'>
        <Link to={`/recipes/${recipe.id}`}>
          <img src={recipe.image_link} alt='Recipe' className='content__pic' />
        </Link>
        <div className='content__desc'>
          <h3 className='content__heading'>
            <Link to={`/receipts/${recipe.id}`}>{recipe.name}</Link>
          </h3>
          <pre className='content__description'>{recipe.products}</pre>
          {clickHandler ? <button className='content__add' onClick={() => clickHandler(recipe)}>
            Add to favourites
          </button> : <></>}
        </div>
      </div>
    </div>
  );
}

export default Recipe;

// src/client/src/components/Recipe.vue
<template>
  <div class="content__recipes">
    <div class="content__recipe">
      <router-link :to="{ path: `/recipes/${recipe.id}` }">
        <img :src="recipe.image_link" alt="Recipe" class="content__pic" />
      </router-link>
      <div class="content__desc">
        <h3 class="content__heading">
          <router-link :to="{ path: `/recipes/${recipe.id}` }">{{
            recipe.name
          }}</router-link>
        </h3>
        <pre class="content__description">{{ recipe.products }}</pre>
        <button class="content__add" @click="$emit('addRecipe', recipe)">
          Add to favourites
        </button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Recipe',
  props: {
    recipe: Object,
  },
};
</script>

<style scoped></style>
