// src/client/src/components/Recipe.vue
<template>
  <div class="content__recipes">
    <div class="content__recipe">
      <router-link :to="{ path: `/recipes/${recipe.id}` }">
        <img :src="recipe.image_link" alt="Recipe" class="content__pic" />
      </router-link>
      <div class="content__desc">
        <h3 class="content__heading">
          <router-link :to="{ path: `/recipes/${recipe.id}` }">{{
            recipe.name
          }}</router-link>
        </h3>
        <pre class="content__description">{{ recipe.products }}</pre>
        <button class="content__add" @click="$emit('addRecipe', recipe)">
          Add to favourites
        </button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Recipe',
  props: {
    recipe: Object,
  },
};
</script>

<style scoped></style>

// src/client/src/components/Recipe.tsx
import React from 'react';
import { Recipe } from '../services/models/Recipe';
import { Link } from 'react-router-dom';
interface Props {
  recipe: Recipe,
  clickHandler: (recipe: Recipe) => void,
  deleteHandler: (recipe: Recipe) => void
}

function Recipe({ recipe, clickHandler, deleteHandler }: Props) {
  return (
    <div className='content__recipes'>
      <div className='content__recipe'>
        <Link to={`/recipes/${recipe.id}`}>
          <img src={recipe.image_link} alt='Recipe' className='content__pic' />
        </Link>
        <div className='content__desc'>
          <h3 className='content__heading'>
            <Link to={`/receipts/${recipe.id}`}>{recipe.name}</Link>
          </h3>
          <pre className='content__description'>{recipe.products}</pre>
          {clickHandler && <button className='content__add' onClick={() => clickHandler(recipe)}>
            Add to favourites
          </button>}
          {deleteHandler && <button className='content__add' onClick={() => deleteHandler(recipe)}>
            Delete from favourites
          </button>}
        </div>
      </div>
    </div>
  );
}

export default Recipe;
