// src/client/src/pages/User.jsx
import React from 'react';
import { useSelector } from 'react-redux';
import Recipe from '../components/Recipe';

function User() {
  const userRecipes = useSelector(state => state.account.userRecipes);

  return (
    <main className='container'>
      <div className='content'>
        <h3>Here is your precious recipes you added to favourites</h3>
        {userRecipes ? <div className='content__recipes'>
          {userRecipes.map((recipe, index) => <Recipe recipe={recipe} key={index} />)}
        </div> :
          <h3>No recipes</h3>}
      </div>
    </main>
  );
}

export default User;

// src/client/src/components/User.vue
<template>
  <main class="container">
    <div class="content">
      <h3>Here is your precious recipes you added to favourites</h3>
      <div v-if="recipes" class="content__recipes">
        <Recipe v-for="recipe of recipes" :key="recipe.id"></Recipe>
      </div>
      <h3 v-else>No recipes</h3>
    </div>
  </main>
</template>

<script>
import Recipe from '@/components/Recipe';

export default {
  name: 'User',
  components: {
    Recipe,
  },
  data() {
    return {
      recipes: null,
    };
  },
};
</script>

<style scoped></style>
